### ISSUE TITLE
Anoxic Mob Removal Function Targeting Main Dimension (Overworld)

### ISSUE THREAD

**Issue by elder-sign** [oitsjustjose/Harmonious-Engineering#11]
Since the 3.1.3 update all passive mobs have disappeared from dim 0 and most likely related there are now severe TPS issues corresponding with entities flickering in and out of existence.

**Comment by oitsjustjose** [comment]
Oh jeez! I tested that tick function I made rather thoroughly but clearly I missed something!

I'm working on a new V-Tweaks feature to help with this significantly anyways, so I will be updating the pack today with a fix. Thanks for the notice!

**Comment by oitsjustjose** [comment]
I've archived 3.1.3 and have a fix releasing shortly. The fix is pushed through for now using the much nicer V-Tweaks implementation I wrote earlier today. Once that update to V-Tweaks is approved, I'll be able to update it in the pack formally.

Thanks for letting me know, and I'm really sorry about your farm & zoo in the LP world 😢
